### ISSUE TITLE
NullPointerException in hrv.band.app.storage.SQLite.SQLController.saveData

### ISSUE THREAD

**Issue by thomcz** [thomcz/hrv-band#116]
User reports that if he enters no note after a measurement the app crashes:

Stacktrace:
```
java.lang.IllegalStateException: Could not execute method of the activity
	at android.view.View$1.onClick(View.java:3843)
	at android.view.View.performClick(View.java:4458)
	at android.view.View$PerformClick.run(View.java:18618)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5310)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at android.view.View$1.onClick(View.java:3838)
	... 11 more
Caused by: java.lang.NullPointerException
	at hrv.band.app.storage.SQLite.SQLController.saveData(SQLController.java:55)
	at hrv.band.app.view.HRVMeasurementActivity.saveMeasurement(HRVMeasurementActivity.java:50)
	... 14 more
```

User device:
```

Hersteller
    Lenovo Mobile
Android-Version
    Android 4.4
RAM (MB)
    1024
Bildschirmgröße
    540 × 960
Bildschirmdichte (dpi)
    240
OpenGL ES-Version
    3.0
Native Plattform
    armeabi-v7a
CPU-Marke
    Qualcomm
CPU-Modell
    MSM8916 
```

**Comment by thomcz** [comment]
the problem might be in the getCategory operation:
```
 valuesParams.put(HRVParameterContract.HRVParameterEntry.COLUMN_NAME_CATEGORY, parameter.getCategory().toString());
```

**Comment by Fenox** [comment]
Möglicher weise liegt das Problem im SQLController, wenn der HRVParameter in note ein null stehen hat.

**Comment by thomcz** [comment]
ich teste es daheim, obs an category oder an der note liegt... nach letztem commit sollte da auch keine null mehr, in beiden fällen zurückgegeben, werden

**Comment by Fenox** [comment]
okay, und ich habe im Controller eine check eingefügt, der prüft ob note null ist.

**Comment by thomcz** [comment]
konnte den Fehler reproduzieren, wenn HRVParameters.getCategory null zurückgibt

**Comment by Fenox** [comment]
Wie kann es sein, dass dort null zurückgegeben wird?

**Comment by thomcz** [comment]
ich habs hart reingecoded, dann kam der gleiche fehler. Bei getNote kam nichts. Momentan sollte nie null zurückkommen, sonder entwerder Category.General oder n leerer string (""), aber man sollte irgwo nen null check machen...ich weiß nur nicht wo...vllt tatsächlich ich sql controller, momentan hab ichs in HRVParameters reingemacht, aber weiß nicht ob des clean code mäßig sinnvoll ist...

**Comment by Fenox** [comment]
ist jetzt auch im SQL controller drin.

**Comment by Fenox** [comment]
kommt der Fehler immer noch?

**Comment by thomcz** [comment]
oh, hab den wohl ausversehen wieder aufgamacht...
