### ISSUE TITLE
The app crashes in the first minute of measurements.

### ISSUE THREAD

**Issue by thomcz** [thomcz/hrv-band#76]
User reports that app crashes in first minute of measurement:

Exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at hrv.band.app.view.UiHandlingUtil.updateTextView(UiHandlingUtil.java:32)
	at hrv.band.app.view.fragment.MeasuringFragment$3.onAnimationEnd(MeasuringFragment.java:137)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```
Device:
```
Galaxy S4
Hersteller: Samsung 
Android-Version: 5.0 
RAM (MB): 2048 
Bildschirmgröße: 1920 × 1080 
Bildschirmdichte (dpi): 480 
OpenGL ES-Version: 2.0 
Native Plattform: armeabi-v7a 
CPU-Marke: Samsung 
CPU-Modell: Exynos5410
```

**Comment by thomcz** [comment]
Could not reproduce. maybe fixed with #55. if not open again
